### ISSUE TITLE
CoC popup location

### ISSUE THREAD

**Issue by thilofischer** [folke/zen-mode.nvim#34] opened 2021-08-12 09:55 UTC
(I don't know if this is a problem with zen-mode or something else.)

When using zen-mode with `coc-clangd` the popups are not displayed at the correct location. Instead of the position of the zen window, the underlying split position is used to compute the location.

In the image, the information from coc is shifted to the left. (The popup menu for autocompletion works fine.)
![zen-mode](https://user-images.githubusercontent.com/24853577/129176658-a89f3249-ad99-4d7d-8733-5c7c29be3cf2.png)

**Comment by oblitum** [comment] 2021-09-27 01:25
duplicate of #14.

**Closed** 2021-09-27 08:14 UTC

**Comment by oblitum** [comment] 2021-09-27 13:48
fwiw, this got fixed on nvim 0.5.1 just released (already on arch repositories).
